# Generated by Django 5.0.6 on 2024-05-23 22:18

import django.utils.timezone
import minify.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlMapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.URLField(max_length=10000)),
                ('short_code', models.CharField(max_length=15, unique=True)),
                ('total_visits', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('last_visit', models.DateTimeField(null=True)),
                ('expires_at', models.DateTimeField(default=minify.models.get_expires_at)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Url Mapping',
                'verbose_name_plural': 'Url Mappings',
                'indexes': [models.Index(fields=['short_code'], name='minify_urlm_short_c_0395fb_idx')],
            },
        ),
    ]
