# Generated by Django 5.0.6 on 2024-05-25 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlmapping',
            name='last_visit',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
